#!/usr/bin/env php
<?php
/**
 * 4KitchenBoard – Token Generator
 *
 * Run this script once from the command line to create a cryptographically
 * secure random token and write it to config.php:
 *
 *   php generate_token.php
 *
 * The script also prompts for MySQL connection credentials and writes them
 * to config.php.  Edit config.php afterwards if you prefer.
 *
 * Copy the printed token into the app's sync settings (API-Token field) on
 * every device that should be allowed to use this server.
 *
 * Re-running this script overwrites the old token with a new one, which
 * effectively locks out any device that still has the old token.
 */

$configFile = __DIR__ . '/config.php';

// Generate 32 bytes (256 bits) of cryptographically secure random data,
// encoded as a 64-character lowercase hex string.
$token = bin2hex(random_bytes(32));
$generatedAt = date('Y-m-d H:i:s');

// Read MySQL credentials from environment or prompt interactively.
$dbHost = getenv('KB_DB_HOST') ?: 'localhost';
$dbName = getenv('KB_DB_NAME') ?: 'kitchenboard';
$dbUser = getenv('KB_DB_USER') ?: '';
$dbPass = getenv('KB_DB_PASS') ?: '';

// When running interactively (not piped), ask for credentials.
if (defined('STDIN') && stream_isatty(STDIN)) {
    echo "MySQL host   [localhost]: ";
    $input = trim(fgets(STDIN));
    if ($input !== '') { $dbHost = $input; }

    echo "MySQL database [kitchenboard]: ";
    $input = trim(fgets(STDIN));
    if ($input !== '') { $dbName = $input; }

    echo "MySQL user: ";
    $input = trim(fgets(STDIN));
    if ($input !== '') { $dbUser = $input; }

    echo "MySQL password: ";
    $input = trim(fgets(STDIN));
    if ($input !== '') { $dbPass = $input; }
}

$dbHostEsc = var_export($dbHost, true);
$dbNameEsc = var_export($dbName, true);
$dbUserEsc = var_export($dbUser, true);
$dbPassEsc = var_export($dbPass, true);

$content = <<<PHP
<?php
/**
 * 4KitchenBoard – API access-token and database configuration
 *
 * Generated by generate_token.php on $generatedAt.
 * Set API_TOKEN to a non-empty string to require every API request to
 * supply a matching token in the X-Api-Token HTTP header.
 * Leave it empty ('') to disable token checking (open access – trusted
 * local network only).
 *
 * !! Keep this file private – never commit it or expose it via HTTP.
 * The accompanying .htaccess already blocks direct HTTP access.
 */

define('API_TOKEN', '$token');

// MySQL connection settings
define('DB_HOST', $dbHostEsc);
define('DB_NAME', $dbNameEsc);
define('DB_USER', $dbUserEsc);
define('DB_PASS', $dbPassEsc);
PHP;

file_put_contents($configFile, $content . PHP_EOL);

echo PHP_EOL;
echo "Token generated and saved to config.php" . PHP_EOL;
echo PHP_EOL;
echo "Your API token:" . PHP_EOL;
echo "  " . $token . PHP_EOL;
echo PHP_EOL;
echo "Server URL for the app (replace with your server address):" . PHP_EOL;
echo "  http://<server-ip>/apps/kitchenboard/api.php" . PHP_EOL;
echo PHP_EOL;
echo "Copy the token into the app's sync settings on every authorised device." . PHP_EOL;
echo "Re-running this script will generate a new token and revoke the old one." . PHP_EOL;
