#!/usr/bin/env php
<?php
/**
 * 4KitchenBoard – Token Generator
 *
 * Run this script once from the command line to create a cryptographically
 * secure random token and write it to config.php:
 *
 *   php generate_token.php
 *
 * Copy the printed token into the app's sync settings (API-Token field) on
 * every device that should be allowed to use this server.
 *
 * Re-running this script overwrites the old token with a new one, which
 * effectively locks out any device that still has the old token.
 */

$configFile = __DIR__ . '/config.php';

// Generate 32 bytes (256 bits) of cryptographically secure random data,
// encoded as a 64-character lowercase hex string.
$token = bin2hex(random_bytes(32));
$generatedAt = date('Y-m-d H:i:s');

$content = <<<PHP
<?php
/**
 * 4KitchenBoard – API access-token configuration
 *
 * Generated by generate_token.php on $generatedAt.
 * Set API_TOKEN to a non-empty string to require every API request to
 * supply a matching token in the X-Api-Token HTTP header.
 * Leave it empty ('') to disable token checking (open access – trusted
 * local network only).
 *
 * !! Keep this file private – never commit it or expose it via HTTP.
 * The accompanying .htaccess already blocks direct HTTP access.
 */

define('API_TOKEN', '$token');
PHP;

file_put_contents($configFile, $content . PHP_EOL);

echo "Token generated and saved to config.php" . PHP_EOL;
echo PHP_EOL;
echo "Your API token:" . PHP_EOL;
echo "  " . $token . PHP_EOL;
echo PHP_EOL;
echo "Copy this token into the app's sync settings on every authorised device." . PHP_EOL;
echo "Re-running this script will generate a new token and revoke the old one." . PHP_EOL;
